env: "local" # local, dev, prod
storage_path: "./storage/storage.db"
http_server:
  address: "localhost:8082"
  timeout: 4s # time to read request and send request (equal time)
  idle_timeout: 60s # connection life-time with client
  user: "myuser"
  password: "mypass"
